
name: Build Flutter APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          cd flutter_app
          flutter pub get
      - name: Build APK
        run: |
          cd flutter_app
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
