name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Get packages
        run: flutter pub get
        working-directory: flutter_app
      - name: Build APK
        run: flutter build apk --release
        working-directory: flutter_app
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
